package com.android.davidgj.cajeroautomaticose.lib;

/**
 * Created by Thanos on 11/1/2017.
 */


//INTERFACE ENVOLTORIO PARA DEFINIR QUE ES LO QUE NOS INTERESA DE LA LIBRERIA EVENTBUS
public interface EventBusHelper {

    //NOS INTERESA Q NOS PODAMOS REGISTRAR AL BUS ATRAVES DE UN OBJETO
    void register(Object subscriber);

    //NOS INTERESA Q NOS PODAMOS DESREGISTRAR CON UN OBJETO SUSCRIPTOR Q SERIA EL PRESENTADOR
    //PERO COMO USAMOS EL PRESENTADOR PARA LOGIN PARA CONTACTS LIST Y DEMAS FITCHUR LO MANEJAMOS COMO UN OBJETO
    void unregister(Object subscriber);


    //VAMOS A QUERER PUBLICAR UN EVENTO PARA POSTERIOR CONSUMIR ESE EVENTO DESDE EL PRESENTADOR
    void post(Object event);

    //

}

